pages = [{"l":"index.html","n":"GUI-1 GUI Demo","t":"GUI-1 GUI Demo","d":"","k":"static"},
{"l":"_empty_.html","n":"<empty>","t":"package <empty>","d":"<empty>","k":"package"},
{"l":"_empty_/Blackjack$.html","n":"Blackjack","t":"object Blackjack","d":"<empty>/Blackjack$","k":"object"},
{"l":"_empty_/Blackjack$.html","n":"main","t":"def main(): Unit","d":"<empty>/Blackjack$","k":"def"},
{"l":"_empty_/main.html","n":"main","t":"class main","d":"<empty>/main","k":"class"},
{"l":"_empty_/main.html","n":"main","t":"def main(args: Array[String]): Unit","d":"<empty>/main","k":"def"},
{"l":"Gui_components.html","n":"Gui_components","t":"package Gui_components","d":"Gui_components","k":"package"},
{"l":"Gui_components/Controller.html","n":"Controller","t":"class Controller(view: View, model: Model)","d":"Gui_components/Controller","k":"class"},
{"l":"Gui_components/Controller.html","n":"advancePlayerOrder","t":"def advancePlayerOrder: Action","d":"Gui_components/Controller","k":"def"},
{"l":"Gui_components/Controller.html","n":"checkForWinner","t":"def checkForWinner: Action","d":"Gui_components/Controller","k":"def"},
{"l":"Gui_components/Controller.html","n":"dealerturn","t":"var dealerturn: Boolean","d":"Gui_components/Controller","k":"var"},
{"l":"Gui_components/Controller.html","n":"doGame","t":"def doGame: Action","d":"Gui_components/Controller","k":"def"},
{"l":"Gui_components/Controller.html","n":"doMove","t":"def doMove: Action","d":"Gui_components/Controller","k":"def"},
{"l":"Gui_components/Controller.html","n":"doRound","t":"def doRound: Action","d":"Gui_components/Controller","k":"def"},
{"l":"Gui_components/Controller.html","n":"doTurn","t":"def doTurn: Action","d":"Gui_components/Controller","k":"def"},
{"l":"Gui_components/Controller.html","n":"exit","t":"def exit: Action","d":"Gui_components/Controller","k":"def"},
{"l":"Gui_components/Controller.html","n":"initializeGame","t":"def initializeGame: Action","d":"Gui_components/Controller","k":"def"},
{"l":"Gui_components/Controller.html","n":"newRound","t":"def newRound: Action","d":"Gui_components/Controller","k":"def"},
{"l":"Gui_components/Controller.html","n":"pos","t":"var pos: Int","d":"Gui_components/Controller","k":"var"},
{"l":"Gui_components/Controller.html","n":"setPlayerStrategy","t":"def setPlayerStrategy(plr: String, strat: String): Unit","d":"Gui_components/Controller","k":"def"},
{"l":"Gui_components/Controller.html","n":"showGameArea","t":"def showGameArea: Action","d":"Gui_components/Controller","k":"def"},
{"l":"Gui_components/Controller.html","n":"showPlayerOrder","t":"def showPlayerOrder: Action","d":"Gui_components/Controller","k":"def"},
{"l":"Gui_components/Controller.html","n":"showStrategy","t":"def showStrategy: Action","d":"Gui_components/Controller","k":"def"},
{"l":"Gui_components/Controller.html","n":"shuffle","t":"def shuffle: Action","d":"Gui_components/Controller","k":"def"},
{"l":"Gui_components/Model.html","n":"Model","t":"class Model","d":"Gui_components/Model","k":"class"},
{"l":"Gui_components/Model.html","n":"advancePlayerOrder","t":"def advancePlayerOrder: String","d":"Gui_components/Model","k":"def"},
{"l":"Gui_components/Model.html","n":"checkForWinner","t":"def checkForWinner: Option[String]","d":"Gui_components/Model","k":"def"},
{"l":"Gui_components/Model.html","n":"doGame","t":"def doGame: Unit","d":"Gui_components/Model","k":"def"},
{"l":"Gui_components/Model.html","n":"doMove","t":"def doMove: Unit","d":"Gui_components/Model","k":"def"},
{"l":"Gui_components/Model.html","n":"doRound","t":"def doRound: Unit","d":"Gui_components/Model","k":"def"},
{"l":"Gui_components/Model.html","n":"doTurn","t":"def doTurn: Unit","d":"Gui_components/Model","k":"def"},
{"l":"Gui_components/Model.html","n":"initializeGame","t":"def initializeGame: Unit","d":"Gui_components/Model","k":"def"},
{"l":"Gui_components/Model.html","n":"newRound","t":"def newRound: Unit","d":"Gui_components/Model","k":"def"},
{"l":"Gui_components/Model.html","n":"setPlayerStrategy","t":"def setPlayerStrategy(plr: String, strat: String): Unit","d":"Gui_components/Model","k":"def"},
{"l":"Gui_components/Model.html","n":"showGameArea","t":"def showGameArea: String","d":"Gui_components/Model","k":"def"},
{"l":"Gui_components/Model.html","n":"showPlayerOrder","t":"def showPlayerOrder: String","d":"Gui_components/Model","k":"def"},
{"l":"Gui_components/Model.html","n":"shuffle","t":"def shuffle: Unit","d":"Gui_components/Model","k":"def"},
{"l":"Gui_components/View.html","n":"View","t":"class View extends MainFrame","d":"Gui_components/View","k":"class"},
{"l":"Gui_components/View.html","n":"DealerHand","t":"var DealerHand: DealerHandPanel","d":"Gui_components/View","k":"var"},
{"l":"Gui_components/View.html","n":"DealerSpaces","t":"val DealerSpaces: BoxPanel","d":"Gui_components/View","k":"val"},
{"l":"Gui_components/View.html","n":"cardSpaces","t":"val cardSpaces: BorderPanel","d":"Gui_components/View","k":"val"},
{"l":"Gui_components/View.html","n":"controller","t":"var controller: Option[Controller]","d":"Gui_components/View","k":"var"},
{"l":"Gui_components/View.html","n":"gameArea","t":"val gameArea: BorderPanel","d":"Gui_components/View","k":"val"},
{"l":"Gui_components/View.html","n":"init","t":"def init(ctr: Controller, mod: Model): Unit","d":"Gui_components/View","k":"def"},
{"l":"Gui_components/View.html","n":"model","t":"var model: Option[Model]","d":"Gui_components/View","k":"var"},
{"l":"Gui_components/View.html","n":"playerHands","t":"val playerHands: PlayerHands","d":"Gui_components/View","k":"val"},
{"l":"Gui_components/View.html","n":"south","t":"val south: BoxPanel","d":"Gui_components/View","k":"val"},
{"l":"Gui_components/View.html","n":"update","t":"def update: Unit","d":"Gui_components/View","k":"def"},
{"l":"Gui_components/View$DealerHandPanel.html","n":"DealerHandPanel","t":"class DealerHandPanel(orientation: Char) extends Panel","d":"Gui_components/View$DealerHandPanel","k":"class"},
{"l":"Gui_components/View$DealerHandPanel.html","n":"images","t":"var images: ArrayBuffer[BufferedImage]","d":"Gui_components/View$DealerHandPanel","k":"var"},
{"l":"Gui_components/View$DealerHandPanel.html","n":"showAsEmpty","t":"def showAsEmpty: Unit","d":"Gui_components/View$DealerHandPanel","k":"def"},
{"l":"Gui_components/View$DealerHandPanel.html","n":"showCards","t":"def showCards(cards: ArrayBuffer[Card]): Unit","d":"Gui_components/View$DealerHandPanel","k":"def"},
{"l":"Gui_components/View$PlayerHandPanel.html","n":"PlayerHandPanel","t":"class PlayerHandPanel(orientation: Char) extends Panel","d":"Gui_components/View$PlayerHandPanel","k":"class"},
{"l":"Gui_components/View$PlayerHandPanel.html","n":"images","t":"var images: ArrayBuffer[BufferedImage]","d":"Gui_components/View$PlayerHandPanel","k":"var"},
{"l":"Gui_components/View$PlayerHandPanel.html","n":"showAsEmpty","t":"def showAsEmpty: Unit","d":"Gui_components/View$PlayerHandPanel","k":"def"},
{"l":"Gui_components/View$PlayerHandPanel.html","n":"showCards","t":"def showCards(cards: ArrayBuffer[Card]): Unit","d":"Gui_components/View$PlayerHandPanel","k":"def"},
{"l":"Gui_components/View$PlayerHands.html","n":"PlayerHands","t":"class PlayerHands extends ArrayBuffer[PlayerHandPanel]","d":"Gui_components/View$PlayerHands","k":"class"},
{"l":"Gui_components/View$PlayerHands.html","n":"reset","t":"def reset: Unit","d":"Gui_components/View$PlayerHands","k":"def"},
{"l":"game_components.html","n":"game_components","t":"package game_components","d":"game_components","k":"package"},
{"l":"game_components/AggressiveStrat.html","n":"AggressiveStrat","t":"class AggressiveStrat extends Strategy","d":"game_components/AggressiveStrat","k":"class"},
{"l":"game_components/AggressiveStrat.html","n":"name","t":"val name: String","d":"game_components/AggressiveStrat","k":"val"},
{"l":"game_components/AggressiveStrat.html","n":"whenToHit","t":"val whenToHit: Int","d":"game_components/AggressiveStrat","k":"val"},
{"l":"game_components/Card.html","n":"Card","t":"class Card(val value: Int, val suit: String)","d":"game_components/Card","k":"class"},
{"l":"game_components/Card.html","n":"cardName","t":"val cardName: String","d":"game_components/Card","k":"val"},
{"l":"game_components/Card.html","n":"suit","t":"val suit: String","d":"game_components/Card","k":"val"},
{"l":"game_components/Card.html","n":"value","t":"val value: Int","d":"game_components/Card","k":"val"},
{"l":"game_components/Dealer$.html","n":"Dealer","t":"object Dealer","d":"game_components/Dealer$","k":"object"},
{"l":"game_components/Dealer$.html","n":"hand","t":"var hand: ArrayBuffer[Card]","d":"game_components/Dealer$","k":"var"},
{"l":"game_components/Dealer$.html","n":"score","t":"var score: Int","d":"game_components/Dealer$","k":"var"},
{"l":"game_components/Dealer$.html","n":"showHand","t":"def showHand: String","d":"game_components/Dealer$","k":"def"},
{"l":"game_components/Dealer$.html","n":"takeTurn","t":"def takeTurn: Unit","d":"game_components/Dealer$","k":"def"},
{"l":"game_components/Dealer$.html","n":"totalHand","t":"def totalHand: Int","d":"game_components/Dealer$","k":"def"},
{"l":"game_components/Deck$.html","n":"Deck","t":"object Deck extends Stack[Card]","d":"game_components/Deck$","k":"object"},
{"l":"game_components/Deck$.html","n":"createCards","t":"def createCards: Unit","d":"game_components/Deck$","k":"def"},
{"l":"game_components/Deck$.html","n":"draw","t":"def draw: Card","d":"game_components/Deck$","k":"def"},
{"l":"game_components/Deck$.html","n":"newHand","t":"def newHand: Unit","d":"game_components/Deck$","k":"def"},
{"l":"game_components/Deck$.html","n":"shuffle","t":"def shuffle: Unit","d":"game_components/Deck$","k":"def"},
{"l":"game_components/Deck$.html","n":"toShuffle","t":"var toShuffle: Boolean","d":"game_components/Deck$","k":"var"},
{"l":"game_components/GenericStrat.html","n":"GenericStrat","t":"class GenericStrat extends Strategy","d":"game_components/GenericStrat","k":"class"},
{"l":"game_components/GenericStrat.html","n":"name","t":"val name: String","d":"game_components/GenericStrat","k":"val"},
{"l":"game_components/GenericStrat.html","n":"whenToHit","t":"val whenToHit: Int","d":"game_components/GenericStrat","k":"val"},
{"l":"game_components/ModerateStrat.html","n":"ModerateStrat","t":"class ModerateStrat extends Strategy","d":"game_components/ModerateStrat","k":"class"},
{"l":"game_components/ModerateStrat.html","n":"name","t":"val name: String","d":"game_components/ModerateStrat","k":"val"},
{"l":"game_components/ModerateStrat.html","n":"whenToHit","t":"val whenToHit: Int","d":"game_components/ModerateStrat","k":"val"},
{"l":"game_components/Player.html","n":"Player","t":"class Player(val name: String)","d":"game_components/Player","k":"class"},
{"l":"game_components/Player.html","n":"betAmount","t":"val betAmount: Int","d":"game_components/Player","k":"val"},
{"l":"game_components/Player.html","n":"bust","t":"def bust: Unit","d":"game_components/Player","k":"def"},
{"l":"game_components/Player.html","n":"curBet","t":"var curBet: Int","d":"game_components/Player","k":"var"},
{"l":"game_components/Player.html","n":"curMoney","t":"var curMoney: Int","d":"game_components/Player","k":"var"},
{"l":"game_components/Player.html","n":"hand","t":"var hand: ArrayBuffer[Card]","d":"game_components/Player","k":"var"},
{"l":"game_components/Player.html","n":"hit","t":"def hit: Unit","d":"game_components/Player","k":"def"},
{"l":"game_components/Player.html","n":"hitCount","t":"var hitCount: Int","d":"game_components/Player","k":"var"},
{"l":"game_components/Player.html","n":"inGame","t":"var inGame: Boolean","d":"game_components/Player","k":"var"},
{"l":"game_components/Player.html","n":"inRound","t":"var inRound: Boolean","d":"game_components/Player","k":"var"},
{"l":"game_components/Player.html","n":"name","t":"val name: String","d":"game_components/Player","k":"val"},
{"l":"game_components/Player.html","n":"placeBet","t":"def placeBet: Unit","d":"game_components/Player","k":"def"},
{"l":"game_components/Player.html","n":"showBet","t":"def showBet: String","d":"game_components/Player","k":"def"},
{"l":"game_components/Player.html","n":"showHand","t":"def showHand: String","d":"game_components/Player","k":"def"},
{"l":"game_components/Player.html","n":"showMoney","t":"def showMoney: String","d":"game_components/Player","k":"def"},
{"l":"game_components/Player.html","n":"stand","t":"def stand: Unit","d":"game_components/Player","k":"def"},
{"l":"game_components/Player.html","n":"strategy","t":"var strategy: Strategy","d":"game_components/Player","k":"var"},
{"l":"game_components/Player.html","n":"takeTurn","t":"def takeTurn: Unit","d":"game_components/Player","k":"def"},
{"l":"game_components/Player.html","n":"totalHand","t":"def totalHand: Int","d":"game_components/Player","k":"def"},
{"l":"game_components/SafeStrat.html","n":"SafeStrat","t":"class SafeStrat extends Strategy","d":"game_components/SafeStrat","k":"class"},
{"l":"game_components/SafeStrat.html","n":"name","t":"val name: String","d":"game_components/SafeStrat","k":"val"},
{"l":"game_components/SafeStrat.html","n":"whenToHit","t":"val whenToHit: Int","d":"game_components/SafeStrat","k":"val"},
{"l":"game_components/Strategy.html","n":"Strategy","t":"class Strategy","d":"game_components/Strategy","k":"class"},
{"l":"game_components/Strategy.html","n":"name","t":"val name: String","d":"game_components/Strategy","k":"val"},
{"l":"game_components/Strategy.html","n":"whenToHit","t":"val whenToHit: Int","d":"game_components/Strategy","k":"val"},
{"l":"simulation_components.html","n":"simulation_components","t":"package simulation_components","d":"simulation_components","k":"package"},
{"l":"simulation_components/Menu$.html","n":"Menu","t":"object Menu","d":"simulation_components/Menu$","k":"object"},
{"l":"simulation_components/Menu$.html","n":"advancePlayerOrder","t":"def advancePlayerOrder: String","d":"simulation_components/Menu$","k":"def"},
{"l":"simulation_components/Menu$.html","n":"checkForWinner","t":"def checkForWinner: Option[String]","d":"simulation_components/Menu$","k":"def"},
{"l":"simulation_components/Menu$.html","n":"doGame","t":"def doGame: Unit","d":"simulation_components/Menu$","k":"def"},
{"l":"simulation_components/Menu$.html","n":"doMove","t":"def doMove: Unit","d":"simulation_components/Menu$","k":"def"},
{"l":"simulation_components/Menu$.html","n":"doRound","t":"def doRound: Unit","d":"simulation_components/Menu$","k":"def"},
{"l":"simulation_components/Menu$.html","n":"doTurn","t":"def doTurn: Unit","d":"simulation_components/Menu$","k":"def"},
{"l":"simulation_components/Menu$.html","n":"initializeGame","t":"def initializeGame: Unit","d":"simulation_components/Menu$","k":"def"},
{"l":"simulation_components/Menu$.html","n":"newRound","t":"def newRound: Unit","d":"simulation_components/Menu$","k":"def"},
{"l":"simulation_components/Menu$.html","n":"resetPlayerStrategies","t":"def resetPlayerStrategies: Unit","d":"simulation_components/Menu$","k":"def"},
{"l":"simulation_components/Menu$.html","n":"resetTable","t":"def resetTable: Unit","d":"simulation_components/Menu$","k":"def"},
{"l":"simulation_components/Menu$.html","n":"setPlayerStrategy","t":"def setPlayerStrategy(playerName: String, strategy: String): Unit","d":"simulation_components/Menu$","k":"def"},
{"l":"simulation_components/Menu$.html","n":"showGameArea","t":"def showGameArea: String","d":"simulation_components/Menu$","k":"def"},
{"l":"simulation_components/Menu$.html","n":"showPlayerOrder","t":"def showPlayerOrder: String","d":"simulation_components/Menu$","k":"def"},
{"l":"simulation_components/Menu$.html","n":"showPlayerStrategies","t":"def showPlayerStrategies: String","d":"simulation_components/Menu$","k":"def"},
{"l":"simulation_components/playerOrder$.html","n":"playerOrder","t":"object playerOrder extends Queue[Player]","d":"simulation_components/playerOrder$","k":"object"},
{"l":"simulation_components/playerOrder$.html","n":"advance","t":"def advance: Unit","d":"simulation_components/playerOrder$","k":"def"},
{"l":"simulation_components/playerOrder$.html","n":"current","t":"def current: Player","d":"simulation_components/playerOrder$","k":"def"},
{"l":"simulation_components/playerOrder$.html","n":"show","t":"def show: String","d":"simulation_components/playerOrder$","k":"def"},
{"l":"docs/index.html","n":"GUI-1 GUI Demo","t":"GUI-1 GUI Demo","d":"","k":"static"}];